<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251205194930 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE autor (libros VARCHAR(255) NOT NULL, nombre VARCHAR(100) NOT NULL, apellido VARCHAR(100) NOT NULL, fecha_nacimiento TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (libros))');
        $this->addSql('CREATE TABLE editorial (libros VARCHAR(255) NOT NULL, nombre VARCHAR(255) NOT NULL, pais VARCHAR(100) DEFAULT NULL, PRIMARY KEY (libros))');
        $this->addSql('CREATE TABLE libro (editorial VARCHAR(255) NOT NULL, titulo VARCHAR(255) NOT NULL, isbn VARCHAR(13) NOT NULL, fecha_publicacion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (editorial))');
        $this->addSql('CREATE TABLE usuario (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(50) NOT NULL, email VARCHAR(255) NOT NULL, password_hash VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE autor');
        $this->addSql('DROP TABLE editorial');
        $this->addSql('DROP TABLE libro');
        $this->addSql('DROP TABLE usuario');
    }
}
