<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251206135927 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE autor (autor_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(100) NOT NULL, apellido VARCHAR(100) NOT NULL, fecha_nacimiento DATE DEFAULT NULL, PRIMARY KEY (autor_id))');
        $this->addSql('CREATE TABLE editorial (editorial_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, pais VARCHAR(100) DEFAULT NULL, PRIMARY KEY (editorial_id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8F7137543A909126 ON editorial (nombre)');
        $this->addSql('CREATE TABLE libro (libro_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titulo VARCHAR(255) NOT NULL, isbn VARCHAR(13) NOT NULL, fecha_publicacion DATE DEFAULT NULL, editorial_id INT NOT NULL, autor_id INT NOT NULL, PRIMARY KEY (libro_id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5799AD2BCC1CF4E6 ON libro (isbn)');
        $this->addSql('CREATE INDEX IDX_5799AD2BBAF1A24D ON libro (editorial_id)');
        $this->addSql('CREATE INDEX IDX_5799AD2B14D45BBE ON libro (autor_id)');
        $this->addSql('CREATE TABLE usuario (user_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(50) NOT NULL, email VARCHAR(255) NOT NULL, password_hash VARCHAR(255) NOT NULL, PRIMARY KEY (user_id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2265B05DF85E0677 ON usuario (username)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2265B05DE7927C74 ON usuario (email)');
        $this->addSql('ALTER TABLE libro ADD CONSTRAINT FK_5799AD2BBAF1A24D FOREIGN KEY (editorial_id) REFERENCES editorial (editorial_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE libro ADD CONSTRAINT FK_5799AD2B14D45BBE FOREIGN KEY (autor_id) REFERENCES autor (autor_id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE libro DROP CONSTRAINT FK_5799AD2BBAF1A24D');
        $this->addSql('ALTER TABLE libro DROP CONSTRAINT FK_5799AD2B14D45BBE');
        $this->addSql('DROP TABLE autor');
        $this->addSql('DROP TABLE editorial');
        $this->addSql('DROP TABLE libro');
        $this->addSql('DROP TABLE usuario');
    }
}
